// src/components/Portfolio/PortfolioItem.jsx
import React, { useState, useEffect } from 'react';
import './Portfolio.css';

const PortfolioItem = ({ title, gifSrc, appLink, repoLink }) => {
    const [isMobile, setIsMobile] = useState(window.innerWidth <= 768);

    useEffect(() => {
        const handleResize = () => {
            setIsMobile(window.innerWidth <= 768);
        };

        window.addEventListener('resize', handleResize);

        return () => {
            window.removeEventListener('resize', handleResize);
        };
    }, []);

    return (
        <div className="portfolio-item">
            <h3 className="portfolio-title">{title}</h3>
            <img src={gifSrc} alt={title} className="portfolio-gif" />
            <div className="portfolio-buttons">
                {appLink && (
                    <button
                        className={isMobile ? 'view-button' : ''}
                        onClick={() => window.open(appLink, '_blank')}
                    >
                        {isMobile ? 'View' : 'View Application'}
                    </button>
                )}
                {repoLink && (
                    <button
                        className={isMobile ? 'repo-button' : ''}
                        onClick={() => window.open(repoLink, '_blank')}
                    >
                        {isMobile ? 'Repo' : 'GitHub Repository'}
                    </button>
                )}
            </div>
        </div>
    );
};

export default PortfolioItem;

// src/components/Portfolio/PortfolioItem.svelte
<script>
  import styles from './Portfolio.module.css';

  let {
    title,
    gifSrc,
    appLink = '',
    repoLink = '',
  } = $props();

  let isMobile = $state(false);

  const updateViewport = () => {
    isMobile = window.innerWidth <= 768;
  };

  const openLink = (url) => {
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  $effect(() => {
    updateViewport();
    window.addEventListener('resize', updateViewport);

    return () => {
      window.removeEventListener('resize', updateViewport);
    };
  });
</script>

<article class={styles.portfolioItem}>
  <h3 class={styles.portfolioTitle}>{title}</h3>
  <img src={gifSrc} alt={title} class={styles.portfolioGif} />
  <div class={styles.portfolioButtons}>
    {#if appLink}
      <button type="button" onclick={() => openLink(appLink)}>
        {isMobile ? 'View' : 'View Application'}
      </button>
    {/if}
    {#if repoLink}
      <button type="button" onclick={() => openLink(repoLink)}>
        {isMobile ? 'Repo' : 'GitHub Repository'}
      </button>
    {/if}
  </div>
</article>
