// src/components/NavBar/NavBar.jsx
import React, { useState, useEffect } from 'react';
import './NavBar.css';

const NavBar = () => {
    const [screenSize, setScreenSize] = useState('');

    useEffect(() => {
        const handleResize = () => {
            const width = window.innerWidth;
            if (width >= 1100) {
                setScreenSize('Siwat – | Arm | –     Kanjanapanitkun');
            } else if (width >= 576) {
                setScreenSize('Siwat K. (Arm)');
            } else {
                setScreenSize('Siwat K.');
            }
        };

        window.addEventListener('resize', handleResize);
        handleResize(); // Set initial screen size

        return () => {
            window.removeEventListener('resize', handleResize);
        };
    }, []);

    return (
        <nav className="nav">
            <div className="logo">{screenSize}</div>
        </nav>
    );
};

export default NavBar;

// src/components/NavBar/NavBar.svelte
<script>
  import styles from './NavBar.module.css';

  let screenName = $state('Siwat K.');

  const updateScreenName = () => {
    const width = window.innerWidth;

    if (width >= 1100) {
      screenName = 'Siwat - | Arm | - Kanjanapanitkun';
    } else if (width >= 576) {
      screenName = 'Siwat K. (Arm)';
    } else {
      screenName = 'Siwat K.';
    }
  };

  $effect(() => {
    updateScreenName();
    window.addEventListener('resize', updateScreenName);

    return () => {
      window.removeEventListener('resize', updateScreenName);
    };
  });
</script>

<nav class={styles.nav}>
  <div class={styles.logo}>{screenName}</div>
</nav>
