// src/App.svelte
<script>
  import styles from './App.module.css';
  import NavBar from './components/NavBar/NavBar.svelte';
  import AboutMe from './components/AboutMe/AboutMe.svelte';
  import Gallery from './components/Gallery/Gallery.svelte';
  import Portfolio from './components/Portfolio/Portfolio.svelte';
  import Footer from './components/Footer/Footer.svelte';
</script>

<main class={styles.app}>
  <NavBar />
  <AboutMe />
  <Gallery />
  <Portfolio />
  <Footer />
</main>

// src/App.jsx
import NavBar from './components/NavBar/NavBar';
import AboutMe from './components/AboutMe/AboutMe';
import Gallery from './components/Gallery/Gallery';
import Portfolio from './components/Portfolio/Portfolio';
import Footer from './components/Footer/Footer';
import './App.css';

function App() {
  return (
    <>
      <NavBar />
      <AboutMe />
      <Gallery />
      <Portfolio />
      <Footer />
    </>
  )
}

export default App
